apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.14.10
  labels:
    app: minecraft
    app.kubernetes.io/instance: minecraft
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/version: 5.1.2
    chart: minecraft-5.1.2
    heritage: Helm
    release: minecraft
  name: minecraft
  namespace: minecraft
spec:
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: minecraft
  selector:
    app: minecraft
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft
    app.kubernetes.io/instance: minecraft
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/version: 5.1.2
    chart: minecraft-5.1.2
    heritage: Helm
    release: minecraft
  name: minecraft-rcon
  namespace: minecraft
spec:
  ports:
  - name: rcon
    port: 25575
    protocol: TCP
    targetPort: rcon
  selector:
    app: minecraft
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  labels:
    app: minecraft
    app.kubernetes.io/instance: minecraft
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/version: 5.1.2
    chart: minecraft-5.1.2
    heritage: Helm
    release: minecraft
  name: minecraft-backupdir
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  labels:
    app: minecraft
    app.kubernetes.io/instance: minecraft
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/version: 5.1.2
    chart: minecraft-5.1.2
    heritage: Helm
    release: minecraft
  name: minecraft-datadir
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft
    app.kubernetes.io/instance: minecraft
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/version: 5.1.2
    chart: minecraft-5.1.2
    heritage: Helm
    release: minecraft
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
        app.kubernetes.io/instance: minecraft
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/version: 5.1.2
    spec:
      containers:
      - env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: NEOFORGE
        - name: VERSION
          value: 1.21.1
        - name: DIFFICULTY
          value: easy
        - name: MODE
          value: survival
        - name: MOTD
          value: Welcome to Minecraft on Kubernetes!
        - name: PVP
          value: "false"
        - name: LEVEL_TYPE
          value: DEFAULT
        - name: LEVEL
          value: world
        - name: MODRINTH_DOWNLOAD_DEPENDENCIES
          value: none
        - name: MEMORY
          value: 16000M
        - name: ENABLE_RCON
          value: "true"
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rcon-password
              name: minecraft-rcon
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              key: cf-api-key
              name: minecraft-curseforge
        - name: CF_PARALLEL_DOWNLOADS
          value: "4"
        - name: USE_AIKAR_FLAGS
          value: "true"
        image: itzg/minecraft-server:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - mc-health
          failureThreshold: 80
          initialDelaySeconds: 300
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: minecraft
        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        - containerPort: 25575
          name: rcon
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - mc-health
          failureThreshold: 80
          initialDelaySeconds: 300
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 6000m
            memory: 18000M
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /data
          name: datadir
        - mountPath: /backups
          name: backupdir
          readOnly: true
      - env:
        - name: SRC_DIR
          value: /data
        - name: BACKUP_NAME
          value: bobworld
        - name: INITIAL_DELAY
          value: 10m
        - name: BACKUP_INTERVAL
          value: 24h
        - name: PRUNE_BACKUPS_DAYS
          value: "7"
        - name: PAUSE_IF_NO_PLAYERS
          value: "false"
        - name: SERVER_PORT
          value: "25565"
        - name: RCON_HOST
          value: localhost
        - name: RCON_PORT
          value: "25575"
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rcon-password
              name: minecraft-rcon
        - name: RCON_RETRIES
          value: "5"
        - name: RCON_RETRY_INTERVAL
          value: 10s
        - name: EXCLUDES
          value: '*.jar,cache,logs'
        - name: BACKUP_METHOD
          value: restic
        - name: RESTIC_REPOSITORY
          value: s3:http://garage.irminsul:3900/minecraft-backups/restic
        - name: RESTIC_ADDITIONAL_TAGS
          value: mc_backups
        - name: PRUNE_RESTIC_RETENTION
          value: --keep-within 7d --keep-weekly 5 --keep-monthly 6
        - name: RESTIC_HOSTNAME
          value: bobserver
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-access-key-id
              name: minecraft-restic
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-access-key
              name: minecraft-restic
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: restic-password
              name: minecraft-restic
        image: itzg/mc-backup:latest
        imagePullPolicy: IfNotPresent
        name: minecraft-mc-backup
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /data
          name: datadir
          readOnly: true
        - mountPath: /backups
          name: backupdir
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - emptyDir: {}
        name: tmp
      - name: datadir
        persistentVolumeClaim:
          claimName: minecraft-datadir
      - name: backupdir
        persistentVolumeClaim:
          claimName: minecraft-backupdir
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-curseforge
  namespace: minecraft
spec:
  data:
  - remoteRef:
      key: kv/nekropolis/minecraft/minecraft-curseforge
      property: cf-api-key
    secretKey: cf-api-key
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: minecraft-curseforge
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-rcon
  namespace: minecraft
spec:
  data:
  - remoteRef:
      key: kv/nekropolis/minecraft/minecraft-rcon
      property: rcon-password
    secretKey: rcon-password
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: minecraft-rcon
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-restic
  namespace: minecraft
spec:
  data:
  - remoteRef:
      key: kv/nekropolis/minecraft/minecraft-restic
      property: restic-password
    secretKey: restic-password
  - remoteRef:
      key: kv/nekropolis/minecraft/minecraft-restic
      property: aws-access-key-id
    secretKey: aws-access-key-id
  - remoteRef:
      key: kv/nekropolis/minecraft/minecraft-restic
      property: aws-secret-access-key
    secretKey: aws-secret-access-key
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: minecraft-restic
