apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-curseforge
spec:
  data:
    - secretKey: cf-api-key
      remoteRef:
        key: kv/nekropolis/minecraft/minecraft-curseforge
        property: cf-api-key
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: minecraft-curseforge
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-rcon
spec:
  data:
    - secretKey: rcon-password
      remoteRef:
        key: kv/nekropolis/minecraft/minecraft-rcon
        property: rcon-password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: minecraft-rcon
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s

