apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
# https://github.com/itzg/minecraft-server-charts/tree/master/charts/minecraft
helmCharts:
  - name: minecraft
    namespace: minecraft
    releaseName: minecraft
    repo: https://itzg.github.io/minecraft-server-charts/
    valuesFile: values.yaml
    version: 5.1.2
    skipTests: true
resources:
  - namespace.yaml
  - externalsecrets.yaml
patches:
  - path: patch-delete-secrets.yaml
