# https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml

serviceAnnotations:
  kube-vip.io/loadbalancerIPs: 192.168.14.10
serviceLabels: {}


resources:
  requests:
    memory: 18000M
    cpu: 2000m

# apparently the container does some magic to correctly adjust these flags based on memory available
# https://docker-minecraft-server.readthedocs.io/en/latest/configuration/jvm-options/#enable-aikars-flags
extraEnv:
  USE_AIKAR_FLAGS: "true"
  # the AllTheMods zipfile for servers seems to not work with downloadModpackUrl
  # https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/#generic-pack-files
  GENERIC_PACK: "http://minecraft-modpacks.garage.irminsul:3902/All_the_Mods_10-6.4_ServerFiles.zip"

# Most of these map to environment variables. See Minecraft for details:
# https://hub.docker.com/r/itzg/minecraft-server/
# since we use a big  modpack, we need to give the server some time to start
livenessProbe:
#  command:
#    - mc-health
  initialDelaySeconds: 600
#  periodSeconds: 5
#  failureThreshold: 20
#  successThreshold: 1
#  timeoutSeconds: 1
readinessProbe:
#  command:
#    - mc-health
  initialDelaySeconds: 600
#  periodSeconds: 5
#  failureThreshold: 20
#  successThreshold: 1
#  timeoutSeconds: 1
#startupProbe:
#  command:
#    - mc-health
#  enabled: false
#  failureThreshold: 30
#  periodSeconds: 1

minecraftServer:
  # this is used to derive the -Xms and -Xmx values from one value
  # neat idea, but we want to mess with the JVM options anyway, so lets just do it all
  # in one place
  memory: 16000M

  # TODO: Set these properly without the cutesy wrappers provided by the image
  jvmOpts:
  # the chart dev felt like separating XX Options out was appropriate
  jvmXXopts:


  serviceType: "LoadBalancer"
  servicePort: 25565
  #loadBalancerIP: 192.168.14.10

  eula: "TRUE"
  version: "1.21.1"
  ## https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms
  type: "NEOFORGE"

  #downloadModpackUrl: "http://minecraft-modpacks.garage.irminsul:3902/All_the_Mods_10-6.4_ServerFiles.zip"

  rcon:
    enabled: true
    existingSecret: minecraft-rcon
    secretKey: rcon-password

persistence:
  dataDir:
    enabled: true
    Size: 20Gi
mcbackup:
  enabled: true
  
  # if the backup sidecar can not reach the main container within this time period
  # the sidecar will error out, restarting the whole pod
  initialDelay: 10m

  # glob patterns to ignore  during backup creation
  excludes: "*.jar,cache,logs"
  pruneBackupsDays: 7

  # TODO: figure out how to pass s3 credentials
  backupMethod: restic

  # WARN: When using restic and sharing the `mcbackup.resticRepository` across multiple minecraft server deployments: either `mcbackup.backupName` or `mcbackup.resticHostname` must be unique!
  # Sets `BACKUP_NAME`, defaults to `minecraftServer.worldSaveName`
  backupName: bobworld
  # Required because the container hostname changes on every recreate of the pod which prevents restic from pruning snapshots from previous pods/hostnames
  # Sets `RESTIC_HOSTNAME`
  resticHostname: bobserver


  # TODO: we want to use HTTPS
  resticRepository: "s3:http://garage.irminsul:3900/minecraft-backups/restic"
  # variable to define a space separated list of additional restic tags. see https://hub.docker.com/r/itzg/mc-backup
  resticAdditionalTags: "mc_backups"
  # see https://restic.readthedocs.io/en/latest/060_forget.html
  pruneResticRetention: "--keep-within 7d --keep-weekly 5 --keep-monthly 6"

  resticEnvs:
    RESTIC_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: minecraft-restic
          key: restic-password
    AWS_ACCESS_KEY_ID:
      valueFrom:
        secretKeyRef:
          name: minecraft-restic
          key: aws-access-key-id
    AWS_SECRET_ACCESS_KEY:
      valueFrom:
        secretKeyRef:
          name: minecraft-restic
          key: aws-secret-access-key

  ## Additional minecraft container environment variables
  ## Values can be either variable values or `valueFrom` yaml
  ##
  #extraEnv:
  #  {}
    # some_variable: some value
    # another_variable:
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: status.hostIP

  ## Additional environment variables to add to the mc-backup container from
  ## ConfigMaps and Secrets
  ##
  envFrom: []

  resources:
    requests:
      memory: 512Mi
      cpu: 500m

  repository: itzg/mc-backup
  # TODO: using the latest image is the default, but not cool
  tag: latest
  pullPolicy: IfNotPresent


  persistence:
    backupDir:
      enabled: true
      Size: 10Gi
