# https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml

serviceAnnotations:
  kube-vip.io/loadbalancerIPs: 192.168.14.10
serviceLabels: {}


resources:
  requests:
    memory: 512Mi
    cpu: 500m
minecraftServer:
  serviceType: "LoadBalancer"
  servicePort: 25565
  #loadBalancerIP: 192.168.14.10

  eula: "TRUE"
  version: "1.21.1"
  ## https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms
  type: "NEOFORGE"
